version: "3"
services:
  detect:
    image: cristiando0902/ncnn_rabbitmq:1.0
    command: bash
    # command: bash /source/init.sh
    volumes: 
      - ./:/source
    container_name: "deep-head-pose"
    tty: true
